### ISSUE TITLE
Some bugs with examples

### ISSUE THREAD

**Issue by ChinouneMehdi** [vmagnin/gtk-fortran#129]
I tried to build the gtk-fortran (gtk3 branch) library on both MSYS2 and Ubuntu 18.04.
  
  - With the Release build I faced one problem with "tests" example which run indefinitely, after investigating it looks that the problem is on "tests.f90,line:295"

```fortran
  ! INTEGER(2) ranges from -32768 to 32767
  ! uint16 ranges from 0 to 65535.
    do a = 0, 32767
      b = g_variant_get_uint16(g_variant_new_uint16 (a))
```

Changing it to `a = 0, 32766 ` fix the problem.

 - With the Debug build, the build stop because the examples contains some gnu extensions.
after adding `-fall-intrinsics` the build success but many examples crash when run `make test`

**Comment by vmagnin** [comment]
@ChinouneMehdi I first encountered that problem in 2016 with the ifort compiler:
https://github.com/vmagnin/gtk-fortran/issues/97

But now, it is the same with gfortran 8.2... The loop never ends and it fills the RAM...

The following code is OK and prints "32767   32767" as expected:
```
a=32767
b = g_variant_get_uint16(g_variant_new_uint16 (a))
print *, a, b
```

The following code is OK:
```
    do a = 0, 32766
      print *, a
   end do
   stop
```

But very strangely,  the following code is NOT OK:
```
    do a = 0, 32767
      print *, a
   end do
   stop
```
It never ends and a becomes <0 after 32767 !

Consider the following code:
```
    do a = 0, 32767
      print *, a
      if (a.LT.0) stop
    end do
```
It prints:
```
  ...
  32765
  32766
  32767
 -32768
```
Perhaps I am tired, mad, or... ???

**Comment by vmagnin** [comment]
Consider the following program:
```
program strange

integer(2) :: a

do a = 0, 32767
  print *, a
  if (a.LT.0) stop
end do

end program strange
```

it runs OK with gfortran 4.8, 5.5.0, 6.5.0 but not with 7.3.0, 8.2.0 (Kubuntu 18.10 64 bits).

**Comment by vmagnin** [comment]
After discussing with jerryd, I have modified the tests.f90 code and pushed it in the master and gtk3 branches. From the Fortran standard, that loop can be considered undefined.

**Comment by vmagnin** [comment]
Concerning the GNU Extensions:
some very early examples of the project were not using gtk_main() but a homemade loop with a sleep() function (gnu extension). I have corrected them and pushed in the master and gtk3 branches.

**Comment by ChinouneMehdi** [comment]
"gtkf-sketcher.f90" still contains many extensions : system(), getcwd(), chdir()
which can be replaced by execute_command_line(), execute_command_line("pwd", cmdmsg=...)  and execute_command_line("cd //... )

**Comment by vmagnin** [comment]
> "gtkf-sketcher.f90" still contains many extensions : system(), getcwd(), chdir()
> which can be replaced by execute_command_line(), execute_command_line("pwd", cmdmsg=...) and execute_command_line("cd //... )

Hi Mehdi,
I reopen the issue. If you have time to work on it now, you can help by making a Pull request.

**Comment by vmagnin** [comment]
@ChinouneMehdi Your help is appreciated. I have commit your Pull request.

But when I open the example.glade file and click on the Output>Write files button, the application crashes:
```
$ ./gtkf-sketcher 
At line 240 of file gtk-fortran/sketcher/gtkf-sketcher.f90 (unit = 60)
Fortran runtime error: File already opened in another unit

Error termination. Backtrace:
#0  0x7f084325f95a
#1  0x7f08432604b5
#2  0x7f0843260c9d
#3  0x7f08434608b3
```

**Comment by ChinouneMehdi** [comment]
I tried to reproduce the bug but I got this

```
$./gtkf-sketcher
At line 234 of file gtk-fortran/sketcher/gtkf-sketcher.f90
Fortran runtime error: Actual string length is shorter than the declared one for dummy 
argument 'source' (68/100)
```

I don't this is related to my patch, because I reversed it and the program still crashes.

**Comment by vmagnin** [comment]
@ChinouneMehdi 
I remember having seen the same message during my trials. May be it is related to the "C F string conversion" commits made yesterday in gtk-sup.f90. I don't know. 
We will need to go back in time to understand the problem.

**Comment by vmagnin** [comment]
@ChinouneMehdi 
On my side, after reverting before your patch, the program is OK. The problem appears with the patch. (Note that sometimes it's better to delete entirely the build directory before rebuilding the project).

Your message appears with the Debug build, and mine with the Release build. Probably the error detected line 234 in Debug mode is causing the error line 240 in Release.

**Comment by vmagnin** [comment]
I am progressing:
- A part of the problem was due to spaces in directory name.
- Another problem could be that using execute_command_line is not really equivalent to GNU functions:
https://gcc.gnu.org/onlinedocs/gfortran/EXECUTE_005fCOMMAND_005fLINE.html#EXECUTE_005fCOMMAND_005fLINE

**Comment by ChinouneMehdi** [comment]
On my side I revert the repository before my code.
After cleaning the build directory `rm -r *`
On MinGW-Debug I got
```
$ ./gtkf-sketcher.exe
At line 234 of file D:/dev/gtk-fortran/sketcher/gtkf-sketcher.f90
Fortran runtime error: Actual string length is shorter than the declared one for dummy argument 'source' (53/100)
```
on MinGW-Release
```
$ ./gtkf-sketcher.exe
At line 240 of file D:/dev/gtk-fortran/sketcher/gtkf-sketcher.f90 (unit = 60)
Fortran runtime error: File already opened in another unit
```
On ubuntu-Debug
```
$ ./gtkf-sketcher
At line 234 of file /home/mehdi/dev/gtk-fortran/sketcher/gtkf-sketcher.f90
Fortran runtime error: Actual string length is shorter than the declared one for dummy argument 'source' (68/100)
```
On ubuntu-Release
```
$ ./gtkf-sketcher
 /home/mehdi/dev/gtk-fortran/build/ubuntu-rel/sketcher/example                                                                                                                                                                                                   
total 12
drwxrwxrwx 1 root root    0 Feb 23 21:13 .
drwxrwxrwx 1 root root 4096 Feb 23 21:13 ..
-rwxrwxrwx 1 root root 1469 Feb 23  2019 example.f90
-rwxrwxrwx 1 root root 2716 Feb 23  2019 example.glade
sh: 1: ./usemodules.py: not found
At line 574 of file /home/mehdi/dev/gtk-fortran/sketcher/gtkf-sketcher.f90 (unit = 40)
Fortran runtime error: Cannot open file 'usemodules.txt': No such file or directory
```

**Comment by vmagnin** [comment]
OK. On my side, I have noted that we should not choose the `gtk-fortran/build/sketcher/example.glade` file (which would be copied over itself) but the `gtk-fortran/sketcher/example.glade` file (which will be copied in the `gtk-fortran/build/sketcher/` directory).

Concerning EXECUTE_COMMAND_LINE(), I think it launches a new shell sh and execute the command, then closes the shell (and loses the environment). So I suspect that the commands executed after a `call execute_command_line("cd "//working_dir)` are not executed in the `working_dir` but in the directory of the` ./gtkf-sketcher `executable.

We will see tomorrow...

**Comment by vmagnin** [comment]
Yes, these two programs are not equivalent:
```
! https://gcc.gnu.org/onlinedocs/gfortran/CHDIR.html#CHDIR
PROGRAM test_chdir
  CHARACTER(len=255) :: path
  CALL getcwd(path)
  WRITE(*,*) TRIM(path)
  CALL chdir("/tmp")
  CALL getcwd(path)
  WRITE(*,*) TRIM(path)
END PROGRAM
```
and
```
PROGRAM test_chdir2
  call execute_command_line("pwd")
  call execute_command_line("cd /tmp")
  call execute_command_line("pwd")
END PROGRAM
```
The results are:
```
$ gfortran essai1.f90 && ./a.out
 /home/vmagnin
 /tmp
$ gfortran essai2.f90 && ./a.out
/home/vmagnin
/home/vmagnin
$ 
```

**Comment by ChinouneMehdi** [comment]
for `chdir()` I found this thread [Change of directory in Fortran in a non compiler-specific way](https://stackoverflow.com/questions/26730836/change-of-directory-in-fortran-in-a-non-compiler-specific-way)

**Comment by vmagnin** [comment]
In fact, there is a g_chdir() function in the GLib (stdio.h file):
https://developer.gnome.org/glib/stable/glib-File-Utilities.html#g-chdir

For some reasons I don't remember, the cfwrapper.py script that generates gtk-fortran does not treat the stdio.h file to avoid some problems. Perhaps I will have a look one day at that problem.

In the meantime, we could wrap by hand that function `int g_chdir  (const gchar *path);`

**Comment by vmagnin** [comment]
The following program is running OK (Ubuntu 18.10). I will put the  interface of the `function g_chdir(path) bind(c)` in the gtk-sup.f90 file. But we need to test also under MSYS2.

```
! gfortran -I. glib-auto.f90 gtk.f90 gtk-sup.f90 g_chdir.f90 `pkg-config --cflags --libs gtk+-3.0` -Wall -Wextra -pedantic -std=f2008 -g

program test
use iso_c_binding, only: c_int, c_null_char
implicit none

integer(kind=c_int) :: my_result

interface
    ! int g_chdir (const gchar *path);
    function g_chdir(path) bind(c)
    use iso_c_binding, only: c_int, c_char
    integer(kind=c_int)                  :: g_chdir
    character(kind=c_char), dimension(*) :: path
    end function
end interface

call execute_command_line("pwd")

my_result = g_chdir("/tmp"//c_null_char)
print *, my_result, "=> 0 means OK, -1 NOK"

open(3, file="pwd.txt", action='write')
write(3,'(A)')"that's OK !"
close(3)

call execute_command_line("pwd")
call execute_command_line("cat /tmp/pwd.txt")
call execute_command_line("cat pwd.txt")

end program
```

```
$ ./a.out
/home/vmagnin/gtk-fortran/src
           0 => 0 means OK, -1 NOK
/tmp
that's OK !
that's OK !
$ 
```

**Comment by vmagnin** [comment]
I have put the interface of the `function g_chdir(path) bind(c)` in the gtk-sup.f90 file.

I have updated the gtkf-sketcher.f90 file and have tested it under Ubuntu 18.10.
**Contrary to what I said in a previous message, do choose the `gtk-fortran/build/sketcher/example.glade` file.** I have added some `print *` to show the directories used by the program.

**Comment by vmagnin** [comment]
There is still a problem in MSYS2:
```
2) g_chdir() problem <=           -1
At line 241 of file ... gtk-fortran/sketcher/gtkf-sketcher.f90 (unit = 60)
Fortran runtime error: File already opened in another unit
```

**Comment by vmagnin** [comment]
I close this issue. The MSYS2 problem deserves a new issue.

**Comment by vmagnin** [comment]
g_chdir() is now wrapped automatically by cfwrapper.py and has been removed from gtk-sup.f90
